bjwebb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^openid/', include('openid_provider.urls')),
)

urlpatterns += patterns('bjwebb.views',
    url(r'^p/$', 'projects'), 
    url(r'^p/([-\w\d]+)/$', 'project'), 
    url(r'^posts/$', 'posts'), 
    url(r'^p/([-\w\d]+)/post/([-\w\d]+)/$', 'post'), 
    url(r'^events/$', 'events'), 
    url(r'^p/([-\w\d]+)/event/([-\w\d]+)/$', 'event'), 
)

urlpatterns += patterns('django.contrib.flatpages.views',
    url('^()$', 'flatpage', name='home'),
    url('^(.*/)$', 'flatpage', name='flatpage'),
)

bjwebb/models.py
from django.db import models
from taggit.managers import TaggableManager

class TimeSpan(models.Model):
    class Meta:
        abstract = True
        ordering = ('-ended', '-started', )
    started = models.DateField(null=True, blank=True)
    ended = models.DateField(null=True, blank=True)
    ignore_days = models.BooleanField(default=False)
    
class Project(TimeSpan):
    name = models.CharField(max_length=255, default='')
    slug = models.SlugField()
    text = models.TextField(default='')
    tags = TaggableManager(blank=True)

    external_url = models.CharField(max_length=255, default='', blank=True)
    external_url_name = models.CharField(max_length=255, default='', blank=True)
    source_url = models.TextField(default='', blank=True)
    paid = models.BooleanField(default=False)

    parent = models.ForeignKey('Project', null=True, blank=True)

    def __unicode__(self):
        return self.name

    def source_url_list(self):
        urls = filter(lambda x: x!='', self.source_url.split('\n'))
        return [ (x,x.split('/')[-1])  for x in urls  ]

class Post(models.Model):
    title = models.CharField(max_length=255, default='')
    slug = models.SlugField()
    text = models.TextField(default='')
    tags = TaggableManager(blank=True)
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    project = models.ForeignKey(Project, null=True)

    def __unicode__(self):
        return self.title

class Event(TimeSpan):
    name = models.CharField(max_length=255, default='')
    slug = models.SlugField()
    text = models.TextField(default='')
    tags = TaggableManager(blank=True)

    project = models.ForeignKey(Project, null=True)
    external_url = models.CharField(max_length=255, default='', blank=True)
    external_url_name = models.CharField(max_length=255, default='', blank=True)

    def __unicode__(self):
        return self.name


from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.cache import cache

@receiver(post_save)
def bump_version(sender, **kwargs):
    cache.set('version', cache.version+1, 0, version=1)

bjwebb/views.py
from models import Project, Post, Event
from django.views.generic import DetailView, ListView

class ModalDetailView(DetailView):
    def get_context_data(self, **kwargs):
        context = super(ModalDetailView, self).get_context_data(**kwargs)
        context['post_comment'] = 'post_comment' in self.request.GET 
        return context

class SlugView(ModalDetailView):
    @classmethod
    def as_view(cls, *args, **kwargs):
        view = super(SlugView, cls).as_view(*args, **kwargs)
        def useslug(request, slug):
            return view(request, slug=slug)
        return useslug 

class ProjectSubView(ModalDetailView):
    def get_object(self):
        return self.model.objects.get(slug=self.args[1], project__slug=self.args[0])

projects = ListView.as_view(model=Project)
project = SlugView.as_view(model=Project)

posts = ListView.as_view(model=Post)
post = ProjectSubView.as_view(model=Post)

events = ListView.as_view(model=Event)
event = ProjectSubView.as_view(model=Event)

bjwebb/templates/base.html
{% extends 'bjwebb/base.html' %}

bjwebb/templates/bjwebb/base.html
<!doctype html>
{% load url from future %}
{% load static from staticfiles %}
<html>
{% load flatcontent_tags %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='//fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
  <link href="{% static 'bjwebb/css/screen.css' %}" media="screen, projection" rel="stylesheet" type="text/css" />
  <link href="{% static 'bjwebb/css/print.css' %}" media="print" rel="stylesheet" type="text/css" />
  <!--[if IE]>
      <link href="{% static 'bjwebb/css/ie.css' %}" media="screen, projection" rel="stylesheet" type="text/css" />
  <![endif]-->
<title>{% block title %}{% flatcontent title %}{% endblock %}</title>
{% block extrahead %}
{% endblock %}
</head>
<body>

<div id="root">

<div id="headerWrap">
<div id="header">
<div id="header_inner">
    <h1><a href="{% url 'home' '' %}">{% flatcontent header %}</a></h1>
    <ul class="nav">
        {% block header_home %}
        <li>
        <a href="{% url 'home' '' %}">{% flatcontent home_title %}</a></li>
        {% endblock %}
        {% block header_projects %}
        <li>
        <a href="{% url 'bjwebb.views.projects' %}">{% flatcontent projects_title %}</a></li>
        {% endblock %}
        {% block header_posts %}
        <li>
        <a href="{% url 'bjwebb.views.posts' %}">{% flatcontent posts_title %}</a></li>
        {% endblock %}
        {% block header_events %}
        <li>
        <a href="{% url 'bjwebb.views.events' %}">{% flatcontent events_title %}</a></li>
        {% endblock %}
    </ul>
</div>
</div>
</div>

<div id="content">
{% block content %}
{% endblock %}
</div>

<div id="root_footer"></div>
</div>

<div id="footer">
<div id="footer_inner">
    <div id="footer_right">{% flatcontent footer %}</div>
</div>
</div>

</body>

bjwebb/templates/bjwebb/event_detail.html
{% extends 'bjwebb/base.html' %}
{% load flatcontent_tags %}
{% load url from future %}

{% block header_events %}
<li class="active">
    <h2><a href="{% url 'bjwebb.views.events' %}">{% flatcontent events_title %}</a></h2></li>
{% endblock %}

{% block content %}

<div class="section-short">
<h2>
    {{ event.name }}
</h2>

<div class="subtitle">
    Part of
    <a href="{% url 'bjwebb.views.project' event.project.slug %}">
        {{ event.project.name }}</a>,
    took place
{% include 'bjwebb/nice_dates.html' with object=event %}
</div>
</div>

<div class="section">
{{ event.text|safe|linebreaks }}
</div>

{% if event.external_url %}
<div class="section">
    <h3>
        Links
    </h3>
    {% if event.external_url %}
    <p>
        {% if event.external_url_name %}
        <a href="{{event.external_url}}">{{ external_url_name }}</a>
        {% else %}
        <a href="{{event.external_url}}">{{event.name}}</a>
        {% endif %}
    </p>
    {% endif %}
</div>
{% endif %}

{% include 'bjwebb/comment_sections.html' with object=event %}

{% endblock %}

bjwebb/templates/bjwebb/event_list.html
{% extends 'bjwebb/base.html' %}
{% load flatcontent_tags %}
{% load url from future %}

{% block header_events %}
<li class="active">
    <h2>{% flatcontent events_title %}</h2></li>
{% endblock %}

{% block content %}

{% for event in object_list %}
<div class="section">
{% url 'bjwebb.views.event' event.project.slug event.slug as event_url %}
{% url 'bjwebb.views.project' event.project.slug as project_url %}
<div>
    {% include 'bjwebb/nice_dates.html' with object=event %}
</div>
<h3>
    <a href="{{ event_url }}">
        {{ event.name }}
    </a>
</h3>

<div class="subtitle">
    (Part of
    <a href="{{ project_url }}">
        {{ event.project.name }}</a>)
</div>

{{ event.text|safe|linebreaks }}

</div>
{% endfor %}
{% endblock %}

bjwebb/templates/bjwebb/nice_dates.html
{% if object.ignore_days %}
    {{object.started|date:"F Y"}} &mdash;
    {% if object.ended %}
        {{object.ended|date:"F Y"}}
    {% else %}
        present
    {% endif %}
{% else %}
    {{object.started|date:"jS F Y"}} &mdash;
    {% if object.ended %}
        {{object.ended|date:"jS F Y"}}
    {% else %}
        present
    {% endif %}
{% endif %}

bjwebb/templates/bjwebb/post_detail.html
{% extends 'bjwebb/base.html' %}
{% load flatcontent_tags %}
{% load url from future %}

{% block header_posts %}
<li class="active">
    <h2><a href="{% url 'bjwebb.views.posts' %}">{% flatcontent posts_title %}</a></h2></li>
{% endblock %}

{% block content %}

<div class="section-short">
<h2>
    {{ post.title }}
</h2>

<div class="subtitle">
<ul>
    <li>
    Posted in: 
    <a href="{% url 'bjwebb.views.project' post.project.slug %}">
        {{ post.project.name }}</a>
    </li>
    <li>
        Created: {{ post.created }}
    </li>
    <li>
        Last Updated: {{ post.updated }}
    </li>
</ul>
</div>
</div>

<div class="section">
{{ post.text|safe|linebreaks }}
</div>

{% include 'bjwebb/comment_sections.html' with object=post %}

{% endblock %}

bjwebb/templates/bjwebb/post_list.html
{% extends 'bjwebb/base.html' %}
{% load flatcontent_tags %}
{% load url from future %}

{% block header_posts %}
<li class="active">
    <h2>{% flatcontent posts_title %}</h2></li>
{% endblock %}

{% block content %}

{% for post in object_list %}
<div class="section">
{% url 'bjwebb.views.post' post.project.slug post.slug as post_url %}
{% url 'bjwebb.views.project' post.project.slug  as project_url %}
<h3>
    <a href="{{ post_url }}">
        {{ post.title }}
    </a>
</h3>

<div class="subtitle">
    (Posted in 
    <a href="{{ project_url }}">
        {{post.project.name}}</a> on {{post.created}})
</div>

{{ post.text|safe|linebreaks }}

</div>
{% endfor %}
{% endblock %}

bjwebb/templates/bjwebb/project_detail.html
{% extends 'bjwebb/base.html' %}
{% load flatcontent_tags %}
{% load url from future %}

{% block header_projects %}
<li class="active">
    <h2><a href="{% url 'bjwebb.views.projects' %}">{% flatcontent projects_title %}</a></h2></li>
{% endblock %}

{% block content %}

<div class="section-short">
<h2>{{ project.name }}</h2>

{% if project.started %}
<div class="subtitle">({% include 'bjwebb/nice_dates.html' with object=project %})</div>
{% endif %}
</div>

<div class="section">
{{ project.text|safe|linebreaks }}
</div>

{% if project.source_url_list|length > 0 or project.external_url %}
<div class="section">
    <h3>
        Links
    </h3>
    {% if project.external_url %}
    <p>
        {% if project.external_url_name %}
        <a href="{{project.external_url}}">{{ external_url_name }}</a>
        {% else %}
        <a href="{{project.external_url}}">{{project.name}}</a>
        {% endif %}
    </p>
    {% endif %}

    {% if project.source_url_list|length == 0 %}
    {% elif project.source_url_list|length == 1 %}
    <p>
        <a href="{{ project.source_url_list|first|first }}">Source Code</a>
    </p>
    {% else %}
        <ul>
        <li>Source Code:</li>
        {% for source_url,source_name in project.source_url_list %}
        <li>
        <a href="{{ source_url }}">{{ source_name }}</a>
        </li>
        {% endfor %}
        </ul>
    {% endif %}
</div>
{% endif %}

{% if project.post_set.all %}
<div class="section">
    <h3>
        Posts
    </h3>
    <ul>
    {% for post in project.post_set.all %}
    {% url 'bjwebb.views.post' post.project.slug post.slug as post_url %}
    <li>
        <a href="">
            {{ post.title }}
        </a>
    </li>
    {% endfor %}
    </ul>
</div>
{% endif %}

{% if project.event_set.all %}
<div class="section">
    <h3>
        Events
    </h3>
    <ul>
    {% for event in project.event_set.all %}
    {% url 'bjwebb.views.event' event.project.slug event.slug as event_url %}
    <li>
        <a href="{{ event_url }}">
            {{ event.name }}
        </a>
    </li>
    {% endfor %}
    </ul>
</div>
{% endif %}

{% include 'bjwebb/comment_sections.html' with object=project %}

{% endblock %}

bjwebb/templates/bjwebb/project_list.html
{% extends 'bjwebb/base.html' %}
{% load flatcontent_tags %}
{% load url from future %}

{% block header_projects %}
<li class="active">
    <h2>{% flatcontent projects_title %}</h2></li>
{% endblock %}

{% block content %}

{% for project in object_list %}
<div class="section">

<h3>
    <a href="{% url 'bjwebb.views.project' project.slug %}">
        {{ project.name }}
    </a>
</h3>

{% if project.started %}
<div class="subtitle">({% include 'bjwebb/nice_dates.html' with object=project %})</div>
{% endif %}

{{ project.text|safe|linebreaks }}

</div>
{% endfor %}

{% endblock %}

bjwebb/templates/comments/base.html
../bjwebb/base.html